### ISSUE TITLE
TSMP EURO-CORDEX runtime issues 

### ISSUE THREAD

**Issue by kvrigor** [HPSCTerrSys/eTSMP#1]
The OASIS initialization issue has been fixed(a554e83d). Now we encounter a divide-by-zero error which occurs when COSMO receives CLM fields:

```
[jrc####:31231:0:31231] Caught signal 8 (Floating point exception: integer divide by zero)
==== backtrace (tid:  17984) ====
 0 0x0000000000012cf0 __funlockfile()  :0
 1 0x00000000010c5cd4 receive_fld_2clm_()  .../cosmo5.01/src/oas3/receive_fld_2clm.F90:277
 2 0x00000000007c87af organize_physics_()  .../cosmo5.01/src/organize_physics.f90:1434
 3 0x0000000000837ae0 MAIN__()  .../cosmo5.01/src/lmorg.f90:1163
 4 0x0000000000411422 main()  ???:0
 5 0x000000000003ad85 __libc_start_main()  ???:0
 6 0x000000000041132e _start()  ???:0
=================================
forrtl: severe (71): integer divide by zero
Image              PC                Routine            Line        Source             
lmparbin_pur       0000000001426F5B  for__signal_handl     Unknown  Unknown
libpthread-2.28.s  0000149992E98CF0  Unknown               Unknown  Unknown
lmparbin_pur       00000000010C5CD4  Unknown               Unknown  Unknown
lmparbin_pur       00000000007C87AF  Unknown               Unknown  Unknown
lmparbin_pur       0000000000837AE0  Unknown               Unknown  Unknown
lmparbin_pur       0000000000411422  Unknown               Unknown  Unknown
libc-2.28.so       0000149992AFAD85  __libc_start_main     Unknown  Unknown
lmparbin_pur       000000000041132E  Unknown               Unknown  Unknown
```

**Comment by chartick** [comment]
The problem is in the oasis patching in COSMO. I created a merge request in the GitLab to fix it.
With the fix, TSMP is running.

**Comment by kvrigor** [comment]
thanks for the fix @chartick! I will rebuild COSMO and verify if the fix works.

**Comment by kvrigor** [comment]
I'm getting a compile error:

```bash
$ cmake --build ${BUILD_DIR} --target COSMO5_1
.
.
.
linking parallel program                                                   
ld: .../oas_cos_define.o: in function `oas_cos_define_':                   
oas_cos_define.F90:(.text+0x17d2): undefined reference to `prism_get_freq_'
```

Does your COSMO compile successfully under eTSMP @chartick ? I just remembered that I actually removed the missing snippet in `oas_cos_define.F90` ([c12a5029](https://icg4geo.icg.kfa-juelich.de/ModelSystems/tsmp_src/cosmo5.01_fresh/-/commit/c12a5029ff81fbd95fad7314de8913217f01445b)) since `prism_get_freq()` isn't supported in OASIS3-MCT v5.0 anymore and it doesn't seem to be used during coupling. Could you also share which OASIS version are you using (by running `echo $OASIS_ROOT`)?

**Comment by chartick** [comment]
Okay, I created a new merge request in the gitlab. prism_get_freq() is replaced by prism_get_freqs() with the appropriate variables. Now it also runs with OASIS-MCTv5. The function is only used for debugging but created the divide-by-zero error. Another possibility would have been to comment out some lines in receive_fld_2clm.F90.

**Comment by kvrigor** [comment]
> Okay, I created a new merge request in the gitlab. prism_get_freq() is replaced by prism_get_freqs() with the appropriate variables. Now it also runs with OASIS-MCTv5. The function is only used for debugging but created the divide-by-zero error. Another possibility would have been to comment out some lines in receive_fld_2clm.F90.

It works! Thanks so much for fixing this!
