### ISSUE TITLE
Compilation build error due to duplicate `-lmct`

### ISSUE THREAD

**Issue by jjokella** [HPSCTerrSys/eTSMP#12]
Trying to run the build for `eCLM-ParFlow-PDAF`, I get problems in the final linking stage.

The error is `undefined references` for example for `oas_m_attrvect_mp_exportrlisttochar`.

The problem has been traced to the duplicate linking of `-lmct` libraries. One is generated by OASIS, one by eCLM and they contain different variables.

**Comment by kvrigor** [comment]
I'd fix this on the eCLM side.

**Comment by jjokella** [comment]
I will close the issue, once we have it fixed it in https://github.com/HPSCTerrSys/eCLM/pull/23

**Comment by jjokella** [comment]
Solved by the following commits:
- https://github.com/HPSCTerrSys/eTSMP/pull/9/commits/0ad8e7b135bef67baa0eddbbc98a13218c39c287
- https://github.com/HPSCTerrSys/eTSMP/commit/f3363824b3fe7682c7d3554a67110fa2d85cf62b
